### ISSUE TITLE
Filters Added

### ISSUE THREAD

**Issue by vainrestaurantxy** [vainrestaurantxy/userapp#19]
![image](https://github.com/vainrestaurantxy/userapp/assets/142725247/2afb740b-7400-4b5c-94c5-e5e97cf79050)
The Tags will have these icons. and functionality.

Basically veg non-veg will remain same for drinks if they alcoholic or non-alcoholic  just show both of them... and other three are tags.

Please use Figma for tags images

**Comment by PrathameshSaraf** [comment]
completed
